# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Default

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: |
      |
      $(System.DefaultWorkingDirectory)/_AutomationTest/EPShope/*.csproj
      $(System.DefaultWorkingDirectory)/_AutomationTest/ProductDataApi/*.csproj
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)/publish'
    zipAfterPublish: false

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)/publish'
    Contents: '**'
    TargetFolder: 'C:\WebApp-CD'
    CleanTargetFolder: true
    OverWrite: true

