# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Default

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
    workingDirectory: '$(System.DefaultWorkingDirectory)'



- task: CopyFiles@2
  displayName: 'Copy Files to: C:\WEBSUT'
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    TargetFolder: 'C:\WEBSUT'